site_name: PyVLCB
theme:
  name: material

# This plugin allows mkdocs to read Python docstrings
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src] # Look in the src directory

nav:
  - Home: index.md
  - Reference: reference.md
  - VLCB specs: spec.md

extra_css:
  - stylesheets/extra.css
