name: Publish to TestPyPI

on:
  push:
    branches:
      - main  # This will trigger a test upload every time you push to main
  release:
    types: [published] # This will also trigger if you create a GitHub Release

jobs:
  build-n-publish:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-latest
    # This environment name MUST match what you typed into TestPyPI
    environment:
      name: testpypi
      url: https://test.pypi.org/p/PyVLCB
    permissions:
      id-token: write # Required for Trusted Publishing handshake
      contents: read  # Required to checkout the code

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: python -m pip install build

      - name: Build distribution
        run: python -m build # Creates the sdist and wheel in dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Tells the action to use the TestPyPI server instead of the real one
          repository-url: https://test.pypi.org/legacy/
